// mill plugins under test
import $exec.plugins
// generated by mill
import $exec.shared


import mill._
import mill.define.Command

//val baseDir = build.millSourcePath

def verify(): Command[Unit] =
  T.command {
    ()
  }

object gitSourceProject extends GitSourceModule {}